# AWS Settings
aws:
  region: "ap-southeast-2"
  roles:
    viewer: ""
    provision: ""

# External Services
services:
  zones_url: ""

# Account Mapping (zone_name -> account_id)
account_mapping:
  lz213:2313

# AMI Sources
ami_sources:
  rhel9_ami: ""
  rhel8_ami: ""

# Auto Scaling Groups
asg_stateless:
  cmsnonprod: # landing zone
    - asg_name: ""
      launch_template: ""
      ami: ""
      kms_key: ""
    - asg_name: ""
      launch_template: ""
      ami: ""
      kms_key: ""


# Logging
logging:
  level: "INFO"
  console: true
  file: true
  path: "logs"
  result_logging: true
  verbose_console: false
  structured: false # Enable JSON structured logging
  rotation:
    enabled: true
    max_bytes: 10485760
    backup_count: 5

report:
  path: results
